#include <stdio.h> // Standard Input/Output library for printf

int main(void) {

    // 1. --- THE CGI HEADERS ---
    // First, print the mandatory Content-Type header.
    // This tells the server "what follows is HTML text."
    printf("Content-Type: text/html\n");

    // You can also add a Status header (optional, defaults to 200 OK)
    printf("Status: 200 OK\n");

    // 2. --- THE MANDATORY BLANK LINE ---
    // This single blank line is critical. It separates the
    // headers from the body.
    printf("\n");

    // 3. --- THE HTML BODY (with CSS) ---
    // Now, just print your HTML document to stdout.
    printf("<!DOCTYPE html>\n");
    printf("<html lang=\"en\">\n");
    printf("<head>\n");
    printf("    <meta charset=\"UTF-8\">\n");
    printf("    <title>CGI Styled Page</title>\n");
    printf("    <style>\n");
    printf("        body {\n");
    printf("            font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;\n");
    printf("            background-color: #121212;\n");
    printf("            color: #e1e1e1;\n");
    printf("            margin: 0;\n");
    printf("            padding: 30px;\n");
    printf("            display: grid;\n");
    printf("            place-items: center;\n");
    printf("            min-height: 90vh;\n");
    printf("        }\n");
    printf("        .container {\n");
    printf("            max-width: 700px;\n");
    printf("            padding: 2rem;\n");
    printf("            background-color: #1e1e1e;\n");
    printf("            border: 1px solid #333;\n");
    printf("            border-radius: 10px;\n");
    printf("            box-shadow: 0 5px 20px rgba(0,0,0,0.5);\n");
    printf("        }\n");
    printf("        h1 {\n");
    printf("            color: #00bcd4;\n");
    printf("            border-bottom: 2px solid #00bcd4;\n");
    printf("            padding-bottom: 10px;\n");
    printf("        }\n");
    printf("        p {\n");
    printf("            font-size: 1.1em;\n");
    printf("            line-height: 1.6;\n");
    printf("        }\n");
    printf("        code {\n");
    printf("            background-color: #2a2a2a;\n");
    printf("            border: 1px solid #444;\n");
    printf("            padding: 3px 6px;\n");
    printf("            border-radius: 4px;\n");
    printf("            font-family: 'Courier New', Courier, monospace;\n");
    printf("            color: #ff9800;\n");
    printf("        }\n");
    printf("    </style>\n");
    printf("</head>\n");
    printf("<body>\n");
    printf("    <div class=\"container\">\n");
    printf("        <h1>Hello, Gigachad!</h1>\n");
    printf("        <p>This page was generated by a <strong>C program</strong>.</p>\n");
    printf("        <p>It's running as a traditional CGI script, printing the <code>Content-Type</code> header, a blank line, and then this full HTML document (with CSS) directly to <code>stdout</code>.</p>\n");
    printf("    </div>\n");
    printf("</body>\n");
    printf("</html>\n");

    // Return 0 to show the script executed successfully
    return 0;
}
